/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.AtendimentoListDAO;
import Exception.CadastroAtendimentoException;
import Model.Atendimento;
import Model.Colaborador;
import Model.Empresa;
import Model.ISelecaoVendaView;
import Model.Pesquisa;
import Model.Venda;
import Repositorio.AtendimentoRepositorio;
import javax.swing.JOptionPane;

/**
 *
 * @author felip
 */
public class AtendimentoPesquisaView extends javax.swing.JFrame implements ISelecaoVendaView{

    private CadastroAtendimentoView cadAtendimentoView;
    private Venda venda;
    
    /**
     * Creates new form AtendimentoPesquisaView
     */
    public AtendimentoPesquisaView(CadastroAtendimentoView cadAtendimentoView) {
        this.cadAtendimentoView = cadAtendimentoView;
        initComponents();
    }

    public void abrirAtendimentoPesquisa(){
        AtendimentoRepositorio atendimentoRepositorio = new AtendimentoListDAO();
        Atendimento atendimento = recuperarAtendimentoPesquisa();
        atendimentoRepositorio.salvarAtendimento(atendimento);
        JOptionPane.showMessageDialog(null, "Atendimento aberto com sucesso !");
    }
    
    public Atendimento recuperarAtendimentoPesquisa(){
        //Recuperamos as informações da tela
        Venda venda = this.venda;
        Empresa empresa = cadAtendimentoView.getEmpresa();
        Colaborador responsavel = cadAtendimentoView.getResponsavel();
        int satisfacaoProduto = Integer.parseInt(tfSatisfProdutos.getText());
        int satisfacaoAtendimento = Integer.parseInt(tfSatisfAtendimento.getText());
        String tramite = taTramite.getText();
        //Criamos o atendimento e retornamos
        Atendimento atendimentoPesquisa = new Pesquisa(venda, satisfacaoProduto, satisfacaoAtendimento, responsavel, tramite, empresa);
        return atendimentoPesquisa;
    }
    
    public boolean validaNiveisSatisfacao(){
        int satisfacaoProduto = Integer.parseInt(tfSatisfProdutos.getText());
        int satisfacaoAtendimento = Integer.parseInt(tfSatisfAtendimento.getText());
        if((satisfacaoProduto >= 1 && satisfacaoProduto <= 3) && (satisfacaoAtendimento >= 1 && satisfacaoAtendimento <= 3)){
            return true;
        } else {
            return false;
        }
    }
    
    @Override
    public void carregaVenda(){
        String venda = this.venda.retornaInformacoesCurto();
        tfPedido.setText(venda);
    }
    
    @Override
    public void setVenda(Venda venda){
        this.venda = venda;
    }
    
    public void identificaExcecao() throws CadastroAtendimentoException{
        if(this.venda == null){
            throw new CadastroAtendimentoException("É necessário selecionar uma venda.");
        } else if(tfSatisfAtendimento.getText().isBlank() || tfSatisfProdutos.getText().isBlank() || (validaNiveisSatisfacao() == false)){
            throw new CadastroAtendimentoException("Verificar os níveis de satisfação.");
        } else if(taTramite.getText().isBlank()){
            throw new CadastroAtendimentoException("Campo 'Trâmite' não pode ficar vazio.");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfPedido = new javax.swing.JTextField();
        btBuscarPedido = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        taOrientacoes = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        tfSatisfProdutos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfSatisfAtendimento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taTramite = new javax.swing.JTextArea();
        btCancelar = new javax.swing.JButton();
        btConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Atendimento");

        jLabel3.setText("Atendimento > Novo Atendimento > Pesquisa");

        jLabel1.setText("Pedido:");

        tfPedido.setEditable(false);

        btBuscarPedido.setText("Buscar");
        btBuscarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPedidoActionPerformed(evt);
            }
        });

        taOrientacoes.setEditable(false);
        taOrientacoes.setColumns(20);
        taOrientacoes.setRows(5);
        taOrientacoes.setText("Níveis de Satisfação:\n\t\t1.   Totalmente insatisfeito\n\t\t2.   Parcialmente satisfeito\n\t\t3.   Satisfeito");
        jScrollPane2.setViewportView(taOrientacoes);

        jLabel5.setText("Satisfação com os Produtos:");

        jLabel6.setText("Satisfação com o Atendimento:");

        jLabel2.setText("Trâmite:");

        taTramite.setColumns(20);
        taTramite.setRows(5);
        jScrollPane1.setViewportView(taTramite);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tfPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscarPedido))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tfSatisfProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(tfSatisfAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarPedido))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfSatisfProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfSatisfAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmar)
                    .addComponent(btCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        try {
            identificaExcecao();
            abrirAtendimentoPesquisa();
            cadAtendimentoView.limparTela();
            this.setVisible(false);
        } catch (CadastroAtendimentoException ex) {
            exibirMensagem(ex.getMessage());
        }
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btBuscarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPedidoActionPerformed
        ListaPedidosView listaPedidos = new ListaPedidosView(this);
        listaPedidos.setVisible(true);
    }//GEN-LAST:event_btBuscarPedidoActionPerformed

    public void exibirMensagem(String menssagem){
        JOptionPane.showMessageDialog(null, menssagem);
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtendimentoPesquisaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtendimentoPesquisaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtendimentoPesquisaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtendimentoPesquisaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AtendimentoPesquisaView().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarPedido;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea taOrientacoes;
    private javax.swing.JTextArea taTramite;
    private javax.swing.JTextField tfPedido;
    private javax.swing.JTextField tfSatisfAtendimento;
    private javax.swing.JTextField tfSatisfProdutos;
    // End of variables declaration//GEN-END:variables
}