/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ColaboradorListDAO;
import DAO.EmpresaListDAO;
import Exception.CadastroAtendimentoException;
import Model.Colaborador;
import Model.Empresa;
import Repositorio.ColaboradorRepositorio;
import Repositorio.EmpresaRepositorio;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author felip
 */
public class CadastroAtendimentoView extends javax.swing.JFrame {
    
    /**
     * Creates new form NovoAtendimentoView
     */
    public CadastroAtendimentoView() {
        initComponents();
        carregaComboboxEmpresa();
        carregaComboboxColaborador();
        limparTela();
    }

    public void carregaComboboxEmpresa(){
        try{
            EmpresaRepositorio empresaRepositorio = new EmpresaListDAO();
            Set<Empresa> empresas = empresaRepositorio.recuperarTodasEmpresas();
            for(Empresa empresa : empresas){
                cbEmpresa.addItem(empresa);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Não existem empresas cadastradas!");
        }
    }
    
    public void carregaComboboxColaborador(){
        try {
            ColaboradorRepositorio colaboradorRepositorio = new ColaboradorListDAO();
            List<Colaborador> colaboradores = colaboradorRepositorio.recuperarTodosColaboradores();
            for(Colaborador responsavel : colaboradores){
                cbResponsavel.addItem(responsavel);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não existem colaboradores cadastrados!");
        }
    }
    
    public void abrirTelaTipoAtendimento(String tipoAtendimento){
        if(tipoAtendimento.equals("Divulgação")){
            AtendimentoDivulgacaoView atendimentoDivulgacao = new AtendimentoDivulgacaoView(this);
            atendimentoDivulgacao.setVisible(true);
        } if(tipoAtendimento.equals("Suporte")){
            AtendimentoSuporteView atendimentoSuporteView = new AtendimentoSuporteView(this);
            atendimentoSuporteView.setVisible(true);
        } if(tipoAtendimento.equals("Pesquisa")){
            AtendimentoPesquisaView atendimentoPesquisaView = new AtendimentoPesquisaView(this);
            atendimentoPesquisaView.setVisible(true);
        }
    }
    
    public void limparTela(){
        cbEmpresa.setSelectedIndex(-1);
        cbResponsavel.setSelectedIndex(-1);
        cbTipoAtendimento.setSelectedIndex(-1);
    }
    
    public Empresa getEmpresa(){
        return cbEmpresa.getItemAt(cbEmpresa.getSelectedIndex());
    }
    
    public Colaborador getResponsavel(){
        return cbResponsavel.getItemAt(cbResponsavel.getSelectedIndex());
    }
    
    public void identificaTipoAtendimento() throws CadastroAtendimentoException{
        if(cbEmpresa.getSelectedItem() == null){
            throw new CadastroAtendimentoException("Empresa não selecionada.");
        } else if(cbResponsavel.getSelectedItem() == null){
            throw new CadastroAtendimentoException("Responsável não selecionado.");
        } else if(cbTipoAtendimento.getSelectedItem() == null){
            throw new CadastroAtendimentoException("Tipo de atendimento não selecionado.");
        } else {
            String tipoAtendimento = cbTipoAtendimento.getSelectedItem().toString();
            abrirTelaTipoAtendimento(tipoAtendimento);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbResponsavel = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbTipoAtendimento = new javax.swing.JComboBox<>();
        btCancelar = new javax.swing.JButton();
        btContinuar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbEmpresa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Atendimento");
        setMaximumSize(new java.awt.Dimension(600, 196));
        setMinimumSize(new java.awt.Dimension(600, 196));
        setPreferredSize(new java.awt.Dimension(600, 245));
        setResizable(false);

        jLabel3.setText("Atendimento > Novo Atendimento");

        jLabel2.setText("Responsável:");

        jLabel1.setText("Tipo de Atendimento:");

        cbTipoAtendimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Divulgação", "Suporte", "Pesquisa" }));
        cbTipoAtendimento.setSelectedIndex(-1);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btContinuar.setText("Continuar");
        btContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContinuarActionPerformed(evt);
            }
        });

        jLabel4.setText("Empresa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTipoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbResponsavel, 0, 350, Short.MAX_VALUE)
                            .addComponent(cbEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btContinuar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbTipoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btContinuar)
                            .addComponent(btCancelar))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContinuarActionPerformed
        try {
            identificaTipoAtendimento();
        } catch (CadastroAtendimentoException ex) {
            exibirMensagem(ex.getMessage());
        }
    }//GEN-LAST:event_btContinuarActionPerformed

    public void exibirMensagem(String menssagem){
        JOptionPane.showMessageDialog(null, menssagem);
    }
    
    public void exibirTelaCadastroAtendimento(){
        setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAtendimentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAtendimentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAtendimentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAtendimentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAtendimentoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btContinuar;
    private javax.swing.JComboBox<Empresa> cbEmpresa;
    private javax.swing.JComboBox<Colaborador> cbResponsavel;
    private javax.swing.JComboBox<String> cbTipoAtendimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
