/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author felip
 */
public class MenuInicialView extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicialView
     */
    public MenuInicialView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbSistemaTelemarketing = new javax.swing.JMenuBar();
        mnEntidades = new javax.swing.JMenu();
        miNovoCliente = new javax.swing.JMenuItem();
        miNovaEmpresa = new javax.swing.JMenuItem();
        miNovoColaborador = new javax.swing.JMenuItem();
        miListaEmpresas = new javax.swing.JMenuItem();
        miListaColaboradores = new javax.swing.JMenuItem();
        mnProdutos = new javax.swing.JMenu();
        miNovoProduto = new javax.swing.JMenuItem();
        mnAtendimento = new javax.swing.JMenu();
        miNovoAtendimento = new javax.swing.JMenuItem();
        miListaAtendimentos = new javax.swing.JMenuItem();
        miRelatorioAtedimento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Telemarketing");

        mnEntidades.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mnEntidades.setText("Entidade");
        mnEntidades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miNovoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miNovoCliente.setText("Novo Cliente ...");
        mnEntidades.add(miNovoCliente);

        miNovaEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miNovaEmpresa.setText("Nova Empresa ...");
        mnEntidades.add(miNovaEmpresa);

        miNovoColaborador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miNovoColaborador.setText("Novo Colaborador ...");
        mnEntidades.add(miNovoColaborador);

        miListaEmpresas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miListaEmpresas.setText("Lista Empresas ...");
        mnEntidades.add(miListaEmpresas);

        miListaColaboradores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miListaColaboradores.setText("Lista Colaboradores ...");
        mnEntidades.add(miListaColaboradores);

        mbSistemaTelemarketing.add(mnEntidades);

        mnProdutos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mnProdutos.setText("Produto");
        mnProdutos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miNovoProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miNovoProduto.setText("Novo Produto ...");
        miNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovoProdutoActionPerformed(evt);
            }
        });
        mnProdutos.add(miNovoProduto);

        mbSistemaTelemarketing.add(mnProdutos);

        mnAtendimento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mnAtendimento.setText("Atendimento");
        mnAtendimento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miNovoAtendimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miNovoAtendimento.setText("Novo Atendimento ...");
        mnAtendimento.add(miNovoAtendimento);

        miListaAtendimentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miListaAtendimentos.setText("Lista Atendimentos ...");
        mnAtendimento.add(miListaAtendimentos);

        miRelatorioAtedimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miRelatorioAtedimento.setText("Relatório de Atendimentos ...");
        mnAtendimento.add(miRelatorioAtedimento);

        mbSistemaTelemarketing.add(mnAtendimento);

        setJMenuBar(mbSistemaTelemarketing);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovoProdutoActionPerformed
        CadastroProdutoView cadastroProdutoView = new CadastroProdutoView();
        cadastroProdutoView.setVisible(true);
    }//GEN-LAST:event_miNovoProdutoActionPerformed

    public void exibirTelaMenuInicial(){
        setVisible(true);
    }
    
    public void adicionarAcaoNovoAtendimento(ActionListener acao){
        miNovoAtendimento.addActionListener(acao);
    }
    
    public void adicionarAcaoListaAtendimentos(ActionListener acao){
        miListaAtendimentos.addActionListener(acao);
    }
    
    public void adicionarAcaoRelatorioAtendimentos(ActionListener acao){
        miRelatorioAtedimento.addActionListener(acao);
    }
    
    public void adicionarAcaoNovoCliente(ActionListener acao){
        miNovoCliente.addActionListener(acao);
    }
    
    public void adicionarAcaoNovoColaborador(ActionListener acao){
        miNovoColaborador.addActionListener(acao);
    }
    
    public void adicionarAcaoNovaEmpresa(ActionListener acao){
        miNovaEmpresa.addActionListener(acao);
    }
    
    public void adicionarAcaoSelecaoColaborador(ActionListener acao){
        miListaColaboradores.addActionListener(acao);
    }
    
    public void adicionarAcaoSelecaoEmpresa(ActionListener acao){
        miListaEmpresas.addActionListener(acao);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicialView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mbSistemaTelemarketing;
    private javax.swing.JMenuItem miListaAtendimentos;
    private javax.swing.JMenuItem miListaColaboradores;
    private javax.swing.JMenuItem miListaEmpresas;
    private javax.swing.JMenuItem miNovaEmpresa;
    private javax.swing.JMenuItem miNovoAtendimento;
    private javax.swing.JMenuItem miNovoCliente;
    private javax.swing.JMenuItem miNovoColaborador;
    private javax.swing.JMenuItem miNovoProduto;
    private javax.swing.JMenuItem miRelatorioAtedimento;
    private javax.swing.JMenu mnAtendimento;
    private javax.swing.JMenu mnEntidades;
    private javax.swing.JMenu mnProdutos;
    // End of variables declaration//GEN-END:variables
}
