/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Atendimento;
import Model.Venda;
import java.util.ArrayList;

/**
 *
 * @author felip
 */
public class MenuInicialView extends javax.swing.JFrame {

    private ArrayList<Atendimento> atendimentos;
    private ArrayList<Venda> vendas;
    
    /**
     * Creates new form MenuInicialView
     */
    public MenuInicialView() {
        this.atendimentos = new ArrayList<>();
        this.vendas = new ArrayList<>();
        initComponents();
    }

    public ArrayList<Atendimento> getAtendimentos(){
        return this.atendimentos;
    }
    
    public ArrayList<Venda> getVendas(){
        return this.vendas;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbSistemaTelemarketing = new javax.swing.JMenuBar();
        mnEntidades = new javax.swing.JMenu();
        mnProdutos = new javax.swing.JMenu();
        mnAtendimento = new javax.swing.JMenu();
        miNovoAtendimento = new javax.swing.JMenuItem();
        miListaAtendimentos = new javax.swing.JMenuItem();
        mnPedido = new javax.swing.JMenu();
        miListaPedidos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Telemarketing");

        mnEntidades.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mnEntidades.setText("Entidade");
        mnEntidades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mbSistemaTelemarketing.add(mnEntidades);

        mnProdutos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mnProdutos.setText("Produto");
        mnProdutos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mbSistemaTelemarketing.add(mnProdutos);

        mnAtendimento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mnAtendimento.setText("Atendimento");
        mnAtendimento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miNovoAtendimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miNovoAtendimento.setText("Novo Atendimento ...");
        miNovoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovoAtendimentoActionPerformed(evt);
            }
        });
        mnAtendimento.add(miNovoAtendimento);

        miListaAtendimentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miListaAtendimentos.setText("Lista Atendimentos ...");
        miListaAtendimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListaAtendimentosActionPerformed(evt);
            }
        });
        mnAtendimento.add(miListaAtendimentos);

        mbSistemaTelemarketing.add(mnAtendimento);

        mnPedido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mnPedido.setText("Pedido");
        mnPedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miListaPedidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miListaPedidos.setText("Lista Pedidos ...");
        miListaPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListaPedidosActionPerformed(evt);
            }
        });
        mnPedido.add(miListaPedidos);

        mbSistemaTelemarketing.add(mnPedido);

        setJMenuBar(mbSistemaTelemarketing);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNovoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovoAtendimentoActionPerformed
        CadastroAtendimentoView novoAtendimentoView = new CadastroAtendimentoView(this);
        novoAtendimentoView.setVisible(true);
    }//GEN-LAST:event_miNovoAtendimentoActionPerformed

    private void miListaAtendimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListaAtendimentosActionPerformed
        ListaAtendimentosView listaAtendimentosView = new ListaAtendimentosView(this);
        listaAtendimentosView.setVisible(true);
    }//GEN-LAST:event_miListaAtendimentosActionPerformed

    private void miListaPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListaPedidosActionPerformed
        ListaPedidosView listaPedidosView = new ListaPedidosView(this);
        listaPedidosView.setVisible(true);
    }//GEN-LAST:event_miListaPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicialView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mbSistemaTelemarketing;
    private javax.swing.JMenuItem miListaAtendimentos;
    private javax.swing.JMenuItem miListaPedidos;
    private javax.swing.JMenuItem miNovoAtendimento;
    private javax.swing.JMenu mnAtendimento;
    private javax.swing.JMenu mnEntidades;
    private javax.swing.JMenu mnPedido;
    private javax.swing.JMenu mnProdutos;
    // End of variables declaration//GEN-END:variables
}
